// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsdpbbxtajfswprxagvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzZHBiYnh0YWpmc3dwcnhhZ3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTY2ODMsImV4cCI6MjA2MDAzMjY4M30.F4NU9BH6LOnIIBHdJWLWEVv72Hp1cq2wGp9jYvehP6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);